site_title = "MyArxiv"
limit_days = 7
cache_url = "https://yangzhao1230.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "q-bio.BM"
title = "Biomolecules"

[[sources]]
limit = 150
category = "q-bio.GN"
title = "Genomics"

[[sources]]
limit = 150
category = "q-bio.QM"
title = "Quantitative Methods"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
